export class MembersDTO {
        category: string;
        date_of_birth: string;
        dependent_types: string;
        email: string;
        member_number: number;
        other_names: string;
        schedule_join_date: string;
        sex: string;
        surname: string;
        telephone_number: string;
}

export class PolicyDetailsDTO {
        agent: string;
        authorised: null | any;
        authorization_date: null | any;
        basic_sum_assured: number;
        branch_description: string;
        calculation_type: null | any;
        client: string;
        currency_rate_type: null | any;
        currency_symbol: string;
        current_endorsement_code: null | any;
        effective_date: string;
        endorsement_code: null | any;
        frequency_of_payment: string;
        inception_date: null | any;
        instalment_day: null | any;
        instalment_loan_amount: null | any;
        instalment_month: null | any;
        instalment_premium: null | any;
        master_policy_number: null | any;
        max_entry_age_limit: null | any;
        medical_total_sum_assured: null | any;
        mrl_sum_assured: null | any;
        occupation_of_holder: null | any;
        paid_to_date: null | any;
        pension_category: null | any;
        pension_mode: null | any;
        policy_code: number;
        policy_number: string;
        prepared_by: null | any;
        product_name: string;
        product_short_description: null | any;
        product_type: null | any;
        quotation_number: null | any;
        status: string;
        total_loan_outstanding_amount: null | any;
        total_premium: number;
        underwriting_year: number;
}

export class PartialWithdrawalsDTO {
        pay_method: string;
        payee: string;
        bank_name: string;
        bank_account_name: string;
        bank_account_no: string;
        notification_date: string;
        amount: number;
        narration: string;
}

export class AnnualValuationsDTO {
        valuation_year: number;
        pnbal_valua_date: string;
        interest_rate: number;
        status: string;
        valuation_date: string;
        employer_bal_bf: number;
        employer_amt: number;
        employer_withdrawal_amt: number;
        employer_contri_income: number;
        employer_bal_income: number;
        employer_balance_cf: number;
        employee_balance_bf: number;
        employee_amt: number;
        employee_vol_amt: number;
        employee_withdrawal_amt: number;
        employee_contri_income: number;
        employee_bal_income: number;
        employee_bal_cf: number;
        total_amount: number;
        withdrawal_total: number;
        tot_bal_carried_forward: number;
        total_bal_bf: number;
        period: string;
        authorised_by: string;
        authorised_date: string;
        wef: string;
        wet: string;
        scheme_fund_bf: number;
        total_deductions: number;
        scheme_fund: number;
        employer_retire_held: number;
        total_fund_bal: number;
        policy_number: string;
        inception_date: string;
        policy_code: number;
        client: string;
        endorsement_code: number;
}

export class PolicyClaimsDTO {
        caus_code: null;
        caus_desc: null;
        caus_type: null;
        clm_admitted: string;
        clm_all_prem_paid: null;
        clm_amt_claimed: null;
        clm_amt_to_pay: null;
        clm_close_no_claim: null;
        clm_date: string;
        clm_date_admitted: null;
        clm_date_claim_reported: null;
        clm_date_death_accident: null;
        clm_ddc_code: null;
        clm_death_disability_age: null;
        clm_death_location: null;
        clm_decline_remarks: null;
        clm_exgratia: null;
        clm_exgratia_remarks: null;
        clm_gross_ret_amt: null;
        clm_hosp_claim: null;
        clm_hosp_date_from: null;
        clm_hosp_date_to: null;
        clm_hosp_days: null;
        clm_hosp_inv_amt: null;
        clm_inst_pay_freq: null;
        clm_investigation_needed: null;
        clm_investigation_rpt_received: null;
        clm_investigation_sent: null;
        clm_is_joint: null;
        clm_loan_os_amt: null;
        clm_mem_code: string;
        clm_mem_dob: null;
        clm_mnth_work_days: null;
        clm_no: string;
        clm_no_admit_reason: null;
        clm_no_claim_reason: null;
        clm_nof_inst: null;
        clm_os_loan_calc: null;
        clm_paid_amt: null;
        clm_pay_instalmnts: null;
        clm_payout_prorata_formulae: null;
        clm_pens_amt_to_pay: null;
        clm_pens_paid_amt: null;
        clm_percentage_of_incapacity: null;
        clm_recovered_amt: null;
        clm_recovery_amt: null;
        clm_remarks: null;
        clm_reserve_amt: null;
        clm_retention_pct: null;
        clm_retetion_amt: null;
        clm_reviewed: null;
        clm_reviewed_by: null;
        clm_reviewed_date: null;
        clm_ri_tot_amt: null;
        clm_status: string;
        clm_within_system: null;
        crr_desc: null;
        ddc_desc: null;
        endr_coinsurance: null;
        mem_dob: null;
        mem_no: null;
        mem_uid: null;
        member_display: string;
        member_number: string;
        pcm_loan_int: null;
        pcm_loan_issue_date: null;
        pcm_orig_loan_repayment_prd: null;
        pcm_original_loan_amt: null;
        pol_client_prp_code: null;
        pol_prod_code: null;
}

export class MemberClaimsDTO {
        caus_code: number;
        caus_desc: string;
        caus_type: string;
        clm_admitted: string;
        clm_all_prem_paid: null;
        clm_amt_claimed: number;
        clm_amt_to_pay: number;
        clm_close_no_claim: null;
        clm_date: null;
        clm_date_admitted: null;
        clm_date_claim_reported: string;
        clm_date_death_accident: string;
        clm_ddc_code: null;
        clm_death_disability_age: number;
        clm_death_location: null;
        clm_decline_remarks: null;
        clm_exgratia: null;
        clm_exgratia_remarks: null;
        clm_gross_ret_amt: null;
        clm_hosp_claim: null;
        clm_hosp_date_from: null;
        clm_hosp_date_to: null;
        clm_hosp_days: null;
        clm_hosp_inv_amt: null;
        clm_inst_pay_freq: null;
        clm_investigation_needed: null;
        clm_investigation_rpt_received: null;
        clm_investigation_sent: null;
        clm_is_joint: null;
        clm_loan_os_amt: null;
        clm_mem_code: null;
        clm_mem_dob: null;
        clm_mnth_work_days: null;
        clm_no: string;
        clm_no_admit_reason: null;
        clm_no_claim_reason: null;
        clm_nof_inst: null;
        clm_os_loan_calc: null;
        clm_paid_amt: null;
        clm_pay_instalmnts: null;
        clm_payout_prorata_formulae: null;
        clm_pens_amt_to_pay: null;
        clm_pens_paid_amt: null;
        clm_percentage_of_incapacity: null;
        clm_recovered_amt: null;
        clm_recovery_amt: null;
        clm_remarks: null;
        clm_reserve_amt: null;
        clm_retention_pct: null;
        clm_retetion_amt: null;
        clm_reviewed: null;
        clm_reviewed_by: null;
        clm_reviewed_date: null;
        clm_ri_tot_amt: number;
        clm_status: string;
        clm_within_system: null;
        crr_desc: null;
        ddc_desc: null;
        endr_coinsurance: null;
        mem_dob: null;
        mem_no: string;
        mem_uid: null;
        member_display: string;
        member_number: null;
        pcm_loan_int: null;
        pcm_loan_issue_date: null;
        pcm_orig_loan_repayment_prd: null;
        pcm_original_loan_amt: null;
        pol_client_prp_code: null;
        pol_prod_code: null;
}

export class ReceiptsAllocatedDTO {
        amount: number;
        balance_amount: number;
        cheque_no: null;
        comm_inclusive: string;
        doc_date: null;
        drcr: string;
        gross_amount: number;
        member_allocated_amount: number;
        member_allocated_balance: number;
        pay_method: null;
        pension_allocate: number;
        pension_allocated_amount: number;
        pension_payment_amount: null;
        policy_fee: number;
        prem_orc_comm: number;
        prem_tax: number;
        premium_allocate: number;
        premium_comm: number;
        premium_payment_amount: null;
        receipt_date: string;
        receipt_no: string;
        refunded_amount: number;
        status: string;
        receipt_narration: string;
}

export class PolicyListingDTO {
        policy_number: string;
        policy_code: number;
        inception_date: string | null;
        frequency_of_payment: string;
        underwriting_year: number;
        authorization_date: string | null;
        status: string | null;
        prepared_by: string | null;
        branch_description: string | null;
        product_name: string | null;
        product_short_description: string | null;
        product_type: string | null;
        authorised: string | null;
        current_endorsement_code: number;
        instalment_day: string | null;
        instalment_loan_amount: number | null;
        instalment_month: string | null;
        instalment_premium: number | null;
        total_loan_outstanding_amount: number | null;
        medical_total_sum_assured: number | null;
        calculation_type: string | null;
        currency_rate_type: string | null;
        currency_symbol: string | null;
        occupation_of_holder: string | null;
        mrl_sum_assured: number | null;
        max_entry_age_limit: number | null;
        master_policy_number: string | null;
        pension_mode: string | null;
        agent: string | null;
        client: string | null;
        effective_date: string;
        paid_to_date: string | null;
        quotation_number: string | null;
        basic_sum_assured: number | null;
        total_premium: number | null
        product_code: number;
        endorsement_code: number;
        description: string;
        type: string;
}