FROM node:18

WORKDIR /app

# Copy only package.json and package-lock.json first (cache dependencies)
COPY package*.json ./

# Install all npm dependencies, including your extra packages, in one layer
RUN npm install --legacy-peer-deps \
    && npm install --save html2canvas xlsx @types/html2canvas angular-paystack angular4-paystack --legacy-peer-deps

# Copy the rest of the source code
COPY . .

# Build Angular app
RUN npm run build -- --base-href=/TQV6/ \
    && npm audit fix --force

