export enum API_CONFIG {
  SETUPS_SERVICE_BASE_URL = 'SETUPS_SERVICE',
  IND_MARKETING_SERVICE_BASE_URL = 'MARKETING_SERVICE',
  GRP_QUOTATIONS_SERVICE_BASE_URL = 'QUOTATIONS_SERVICE',
  UNDERWRITING_SERVICE_BASE_URL = 'UNDERWRITING_SERVICE',
  CRM_SETUPS_SERVICE_BASE_URL = 'CRM_SETUPS_SERVICE',
  CRM_ACCOUNTS_SERVICE_BASE_URL = 'CRM_ACCOUNTS_SERVICE',
  JSON_SERVICE_BASE_URL = 'JSON_API_SERVICE',
  NOTIFICATION_BASE_URL = 'NOTIFICATION_SERVICE',
  REPORT_SERVICE_BASE_URL = 'REPORT_SERVICE',

  NONE_BASE_URL = '',
  PREMIUM_COMPUTATION = "PREMIUM_COMPUTATION",
  GIS_REINSURANCE_BASE_URL = 'GIS_REINSURANCE_SERVICE',
  GIS_UNDERWRITING_BASE_URL = 'GIS_UNDERWRITING_SERVICE',
  GIS_SETUPS_BASE_URL = 'GIS_SETUPS_SERVICE',
  GIS_CLAIMS_BASE_URL = 'GIS_CLAIMS_SERVICE',
  MNGT_WORKFLOW_BASE_URL = 'MANAGEMENT_WORKFLOW',

  DMS_SERVICE = 'DMS_SERVICE',
}


export enum API_TENANT_ID {
  LIFECO = 'lifeco',
  MUTUAL = 'mutual',
  FBNI = 'fbni',
  DONEWELL = 'donewell',
  TURNQUEST = 'turnquest',
  STARDISCOVER = 'stardiscover',
  TQV6 = "v6test"

}
