export enum API_CONFIG {
  SETUPS_SERVICE_BASE_URL = 'SETUPS_SERVICE',
  IND_MARKETING_SERVICE_BASE_URL = 'MARKETING_SERVICE',
  GRP_QUOTATIONS_SERVICE_BASE_URL = 'QUOTATIONS_SERVICE',
  UNDERWRITING_SERVICE_BASE_URL = 'UNDERWRITING_SERVICE',
  CRM_SETUPS_SERVICE_BASE_URL = 'CRM_SETUPS_SERVICE',
  JSON_SERVICE_BASE_URL = 'JSON_API_SERVICE',
  NONE_BASE_URL = '',
}


export enum API_TENANT_ID {
  LIFECO = 'lifeco',
  MUTUAL = 'mutual',
  FBNI = 'fbni',
  DONEWELL = 'donewell',
  TURNQUEST = 'turnquest',
  STARDISCOVER = 'stardiscover',
}
