export class EndorsementDetailsDTO {
    endr_no: string;
    endr_duration_type: string;
    endr_status: string;
    endr_tot_sa: number | null;
    endr_tot_premium: number | null;
    endr_type: string;
    endr_pay_method: string;
    endr_effective_date: string;
    endr_prev_sa: number | null;
    endr_prev_prem: number | null;
    agent_display: string;
    endr_freq_of_payment: string;
    endr_cover_to_date: string;
    endr_add_ref_prem: number | null;
    endr_male_nrd: number | null;
    mask_display: string;
    check_agent_display: string | null;
    endr_calc_type: string;
    endr_add_ref_perc_variance: number | null;
    endr_female_nrd: number | null;
    endr_comm_rate: number | null;
    endr_checkoff_rate: number | null;
    endr_nof_members: number | null;
    endr_inst_prem: number | null;
    endr_comm_amt: number;
    endr_pens_type: string | null;
    endr_scheme_type: string | null;
    endr_reg_no: string | null;
    endr_reg_date: string | null;
    endr_scheme_trustees: string | null;
    endr_pens_esc: number | null;
    endr_earn_escalation: number | null;
    endr_nssf_include: boolean | null;
    endr_nssf_amount: number | null;
    endr_pens_tax_complia: boolean | null;
    endr_guarant_prd: number | null;
    endr_pens_pay_freq: string | null;
    endr_contribtn_type: string | null;
    endr_empyer_contr_rate: number | null;
    endr_empyee_contr_rate: number | null;
    endr_pens_admin_fee: number | null;
    endr_empyr_pens_bf: number | null;
    endr_empye_pens_bf: number | null;
    endr_tot_pens_bf: number | null;
    endr_pens_comm_rate: number | null;
    endr_fnding_rate: number | null;
    pens_type: string | null;
    contrib_type: string | null;
    nssf_incl: boolean | null;
    pay_freq: string | null;
    endr_unit_rate_formula: string | null;
    endr_vat_rate: number | null;
    endr_ov_comm_rate: number | null;
    fcl_calc_type: string | null;
    endr_fcl_amt: number | null;
    endr_override_fcl_amt: number | null;
    endr_authorized: boolean | null;
    ta_code: string | null;
    ta_desc: string | null;
    endr_tot_scheme_sa: number | null;
    endr_tot_empyer_contr: number | null;
    endr_tot_empyee_contr: number | null;
    endr_tot_contr: number | null;
    service_provider: string | null;
    endr_ann_type: string | null;
    endr_ann_option: string | null;
    endr_ann_amount: number | null;
    endr_ann_escalation: number | null;
    endr_pens_int_rate: number | null;
    endr_facre_ceding: string | null;
    endr_facre_rate_type: string | null;
    endr_ann_invest_rate: number | null;
    endr_ann_terminal_payout_rate: number | null;
    endr_ann_scheme_legal_age: number | null;
    endr_ann_admin_charge: number | null;
    endr_ann_invest_intr_rate: number | null;
    endr_tot_ann_investments: number | null;
    endr_tot_terminal_benefits: number | null;
    endr_pens_val_frequency: string | null;
    endr_coinsurance: boolean | null;
    endr_coinsure_leader: string | null;
    endr_cover_from_date: string;
    endr_rein_pmas_code: string | null;
    endr_rein_pmas_sht_desc: string | null;
    endr_fcl_calc_type: string;
    endr_duration_term_type: string | null;
    endr_pens_mode: string | null;
    endr_coin_fac_share: number | null;
    endr_mktr_agn_code: string | null;
    marketer: string | null;
    endr_emplyr_volu_contr: number | null;
    endr_emplye_volu_contr: number | null;
    endr_joint_agents: string | null;
    endr_agen_share: number | null;
    endr_umbrella_duration: string | null;
    endr_pmas_code: string | null;
    endr_pmas_sht_desc: string | null;
    total_coin_prem: number | null;
    total_coin_sa: number | null;
    endr_loss_ratio: number | null;
    endr_avg_anb: number | null;
    endr_hist_pens_int_rate: number | null;
    endr_single_gross_rate: string;
    endr_refund_rate: number | null;
    endr_pen_scheme_type: string | null;
    endr_profit_perc: number | null;
    endr_profit_factor: number | null;
    endr_pens_acrual_fctr: number | null;
    endr_pens_inactive_admin_fee: number | null;
    endr_pens_loan_perc: number | null;
    endr_override_comm: number | null;
    endr_clm_exp_rate: number | null;
    endr_cumulative_loss_ratio: number | null;
    endr_admin_fee_type: string | null;
    endr_track_losses: boolean | null;
    endr_loss_period: number | null;
    endr_prem_fraction: number | null;
    endr_pens_ann_fac_rate: number | null;
    endr_tot_prem_paid: number | null;
    endr_tot_claim_paid: number | null;
    endr_claims_float: number | null;
    endr_profit_share_formula: string | null;
    endr_prof_share_prd: string | null;
    endr_rba_reg_no: string | null;
    endr_kra_taxexemption_no: string | null;
    endr_pin_no: string | null;
    commision_basis: string | null;
    endr_facultative_type: string;
    endr_post_past_period: number | null;
    endr_post_past_prd_date: string | null;
    endr_fac_position: string | null;
    endr_facultative_share: number | null;
    endr_docs_dispatch_date: string | null;
    endr_acknmt_date: string | null;
    endr_acknowledged: boolean | null;
    endr_acknmt_by: string | null;
    endr_doc_issued: boolean | null;
    endr_doc_reason: string | null;
    endr_max_age_limit_yrs: number | null;
    endr_prof_share_wef: string | null;
    endr_prof_share_wet: string | null;
    endr_agn_effective_date: string | null;
    endr_inv_rider_allowed: string;
    endr_investment_term: number | null;
    endr_inv_add_ref_amt: number | null;
    endr_existing_fcl: number | null;
    mem_above_fcl: number | null;
    mem_above_existing_fcl: number | null;
    mem_above_override_fcl: number | null;
    endr_debit_note_sent: boolean | null;
    endr_nof_mems_endrsd: number | null;
    endr_cb_comm_type: string | null;
    endr_max_fcl: number | null;
    endr_cb_init_by: string | null;
    endr_past_period: number | null;
    endr_wht_exempted: boolean | null;
    endr_refund_comm_at_ref: number | null;
    endr_bonus_rate: number | null;
    endr_bonus_amt: number | null;
    endr_bonus_allowed: boolean | null;
    endr_jnt_mktr_agn_code: string | null;
    jnt_marketer: string | null;
    endr_emv_term: number | null;
    endr_med_underwrite_status: string | null;
    endr_med_complete_status: string | null;
    endr_vat_amt: number | null;
    total_coin_unused_prem: number | null;
    endr_invoice_status: string | null;
    endr_fac_admin_fee: number | null;
    endr_payee_type: string | null;
    endr_payee: string | null;
    endr_bank_acc_no: string | null;
    endr_bank_acc_name: string | null;
    client_display: string | null;
    branch_name: string | null;
    endr_pay_onlast_todie: boolean | null;
    pay_onlast_todie: boolean | null;
    endr_post_transaction: boolean | null;
    full_sa: number | null;
    full_prem: number | null;
    endr_pens_admin_fee_calc: string | null;
    endr_pens_admin_fee_amt: number | null;
    endr_pens_vat_amt: number | null;
}

export class PolicyDocumentsDTO {
    gpd_code: number;
    gpd_rd_code: number;
    document_display: string;
    gpd_rd_sht_desc: string;
    gpd_is_doc_submitted: string;
    gpd_date_given: string;
    gpd_doc_no: number | null;
}

export class CoverTypesDTO {
    pcvt_cvt_sht_desc: string;
    pcvt_sa: number;
    pcvt_premium: number;
    pcvt_but_charge_premium: number | null;
    cvt_depend_disp: string;
    pcvt_tot_members: number;
    pcvt_load_disc: string;
    pcvt_disc_load_rate: number | null;
    pcvt_disc_load_div_fact: number | null;
    pcvt_average_period: number | null;
    pcvt_sa_per_member: number | null;
    pcvt_use_unit_rate: string;
    pcvt_unit_rate: number;
    pcvt_code: number;
    pcvt_main_rider: string;
    pcvt_cvt_code: number;
    pcvt_avg_anb: number | null;
    pcvt_fcl_amt: number | null;
    pcvt_override_fcl_amt: number | null;
    pcvt_main_sa_perc: number | null;
    pcvt_main_cover: string;
    main_cover_desc: string;
    pcvt_pct_code: number;
    pcvt_loanamt_per_mem: number | null;
    pcvt_loan_rpymt_prd: number | null;
    pcvt_loanint_per_mem: number | null;
    pcvt_savings_per_mem: number | null;
    pcvt_disc: string;
    pcvt_disc_rate: number | null;
    pcvt_disc_div_fact: number | null;
    pcvt_pmas_code: number | null;
    pcvt_pmas_sht_desc: string | null;
    pcvt_rate: number | null;
    pcvt_rate_div_fact: number;
    pcvt_use_cvr_rate: string;
    pcvt_load_age_fact: number | null;
    pcvt_override_ret_limit: number | null;
    pcvt_override_ret_lim_amt: number | null;
    pcvt_tot_member_earnings: number | null;
    pcvt_tot_orig_loan_amt: number | null;
    pcvt_mult_earnings_prd: number | null;
    pcvt_staff_desc: string | null;
    pcvt_avg_mem_earn: number | null;
    pcvt_apply_comm_exp_loading: string | null;
    pcvt_facultative: string;
    pcvt_cover_beneficiaries: string | null;
    pcvt_comm_rate: number | null;
    pcvt_comm_amt: number | null;
    pcvt_waiting_period: number | null;
    pcvt_formular: string;
    pcvt_refund_formular: string;
}

export class CoinsuranceDetailsDTO {
    pol_coin_code: number;
    pol_coin_endr_code: number;
    pol_coin_agn_code: number;
    pol_coin_pol_code: string | null;
    coinsurer_display: string | null;
    pol_coin_admin_fee: number | null;
    pol_coin_share_pct: number | null;
    pol_coinsure_leader: string | null;
    pol_coinsure_leader_share: number | null;
    follower_leader: string | null;
    follower_leader_desc: string | null;
    pol_coin_premium: number | null;
    pol_coin_srvce_fee: number | null;
    endr_coin_follower_share: number | null;
    endr_follower_prem_provided: number | null;
    endr_leader_combined: number | null;
    pol_coin_settled: string | null;
    pol_coin_comm_amt: number | null;
    btr_trans_type: string | null;
    pol_coin_balance: number | null;
    fully_settled: string | null;
    pol_coin_med_fees: number | null;
    tot_coin_sa: number | null;
    pol_coin_ov_comm: number | null;
    pol_coin_vat_amt: number | null;
    lpfp_fac_comm_rate: number | null;
    lpfp_fac_comm_amt: number | null;
}

export class CategoryDTO {
    pca_comm_rate: number | null;
    pca_comm_amt: number | null;
    pmas_sht_desc: string;
    limit_amount: number | null;
    loan_amount: number | null;
    lpag_code: number | null;
    average_cvr_earning_permember: number | null;
    maximum_type_allowed: number | null;
    minimum_amt: number | null;
    cvt_desc: string | null;
    dty_sht_desc: string | null;
    main_cover: string | null;
    cover_inbuilt: string | null;
    sum_assured_percentage: number | null;
    accelerator: number | null;
    level: number | null;
    policy_access_group: string;
    policy_category_code: number;
    short_description: string;
    category_category: string;
    policy_code: string | null;
    period: number;
    med_exempted: number | null;
    endorsement_code: string | null;
    school_code: string | null;
    premium_mask_code: number;
    premium_mask_desc: string;
    previous_category_code: number | null;
    use_cvr_rate: string;
    rate: number | null;
    category_rate_division_factor: number | null;
    average_earnings_per_member: number | null;
    average_anb: number | null;
    sum_assured_per_member: number | null;
    multiple_earnings_period: number | null;
    total_member_earnings: number | null;
    total_original_loan_amount: number | null;
    total_members: number | null;
    sum_assured: number | null;
    premium: number | null;
    base_sum_assured: number | null;
    base_premium: number | null;
    fee_amount: number | null;
    total_students: number | null;
}
